package Vistas;

import AccesoDatos.TipoHabitacionData;
import Entidades.TipoHabitacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matias
 */
public class TipoHabitaciones extends javax.swing.JPanel {

    private TipoHabitacionData thd;
    private TipoHabitacion thactual = null;

    private DefaultTableModel modelo;
private String m ="Modificar";
private String n="Nuevo";

    /**
     *
     */
    public TipoHabitaciones() {
        initComponents();
        thactual = new TipoHabitacion();
        thd = new TipoHabitacionData();

        modelo = new DefaultTableModel();
        mostrar("");
        jbModificar.setText(n);
    }
   

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    private void LimpiarCampos() {
        jtfCodigo.setText("");
        jcCantP.setSelectedIndex(0);
        jtfCantC.setText("");
        jtfCategoriaC.setText("");
        jtfTipoHabitacion.setText("");
        jtfPrecio.setText("");
        jtfTotal.setText("");
        jbModificar.setText(n);
        
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i > 0; i--) {
            modelo.removeRow(i);
        }
    }

    void ocultar_columnas() {//ocultar columna idHabitacion
        jtListaTipoHab.getColumnModel().getColumn(0).setMaxWidth(0);
        jtListaTipoHab.getColumnModel().getColumn(0).setMinWidth(0);
        jtListaTipoHab.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    ////////////////////
    void inhabilitar() {
        jtfCodigo.setVisible(false);
        jtfPrecio.setEnabled(false);
        jcCantP.setEnabled(false);
        jtfCantC.setEnabled(false);
        jtfCategoriaC.setEnabled(false);
        jtfTipoHabitacion.setEnabled(false);

//        jbNuevo.setEnabled(false);
        jbEliminar.setEnabled(false);
    }

    void habilitar() {

        jtfCodigo.setVisible(true);
        jtfPrecio.setEnabled(true);
        jcCantP.setEnabled(true);
        jtfCantC.setEnabled(true);
        jtfCategoriaC.setEnabled(true);
        jtfTipoHabitacion.setEnabled(true);

//        jbNuevo.setEnabled(true);
        jbEliminar.setEnabled(true);
    }

    void mostrar(String buscar) {

        try {
            DefaultTableModel modelo;
            TipoHabitacionData thd = new TipoHabitacionData();
            modelo = thd.mostrar(buscar);

            jtListaTipoHab.setModel(modelo);
            ocultar_columnas();
            jtfTotal.setText("Total de códigos " + Integer.toString(thd.totalRegistros));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jblimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfCategoriaC = new javax.swing.JTextField();
        jtfCantC = new javax.swing.JTextField();
        jtfTipoHabitacion = new javax.swing.JTextField();
        jcCantP = new javax.swing.JComboBox<>();
        jTFID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaTipoHab = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jtfTotal = new javax.swing.JTextField();
        jbLimpiarTabla = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jbCargar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 790));
        setPreferredSize(new java.awt.Dimension(1000, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorías de Habitaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 500));

        jLabel1.setText("Cantidad de Personas ");

        jLabel2.setText("Cantidad de camas");

        jLabel3.setText("Categoria cama ");

        jLabel4.setText("Categoría  Habitación");

        jLabel5.setText("Precio por noche");

        jtfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioActionPerformed(evt);
            }
        });
        jtfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecioKeyTyped(evt);
            }
        });

        jbModificar.setText("Guardar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setActionCommand("Guardar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jblimpiar.setText("Limpiar");
        jblimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Código");

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });

        jtfCategoriaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCategoriaCKeyTyped(evt);
            }
        });

        jtfCantC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCantCKeyTyped(evt);
            }
        });

        jtfTipoHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTipoHabitacionKeyTyped(evt);
            }
        });

        jcCantP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jTFID.setEditable(false);

        jLabel6.setText("  ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jcCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfCantC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtfCategoriaC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTipoHabitacion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 65, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jTFID))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEliminar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jbModificar)
                            .addGap(18, 18, 18)
                            .addComponent(jblimpiar))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCategoriaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jblimpiar))
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(650, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(670, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(670, 400));

        jtListaTipoHab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "Precio x noche"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListaTipoHab.setEnabled(false);
        jtListaTipoHab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaTipoHabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaTipoHab);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtfTotal.setEditable(false);

        jbLimpiarTabla.setText("Limpiar");
        jbLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarTablaActionPerformed(evt);
            }
        });

        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyTyped(evt);
            }
        });

        jbCargar.setText("Cargar");
        jbCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione categoría");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCargar)
                        .addGap(99, 99, 99)
                        .addComponent(jbLimpiarTabla)))
                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCargar)
                    .addComponent(jbLimpiarTabla)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jblimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimpiarActionPerformed
        LimpiarCampos();
       // jbNuevo.setEnabled(true);
        jbModificar.setText("Nuevo");
    }//GEN-LAST:event_jblimpiarActionPerformed


    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed

        //jbNuevo.setEnabled(false);
       // jbModificar.setEnabled(true);
        

        if (jtfCodigo.getText().length() == 0 || jtfCodigo.getText().equals(".")) {

            JOptionPane.showConfirmDialog(null, "debes ingresar el código");
//            jtfCodigo.requestFocus();
            return;
        }
        System.out.println("+");
////        if (jtfPrecio.getText().length() == 0) {

//            JOptionPane.showConfirmDialog(null, "debes ingresar el precio");
////            jtfPrecio.requestFocus();
//            return;
//        }
        System.out.println("++");
        if (jtfCantC.getText().length() == 0) {

            JOptionPane.showConfirmDialog(null, "debes ingresar la cantidad de camas");
            jtfCantC.requestFocus();
            return;
        }
        System.out.println("+++");
        if (jtfCategoriaC.getText().length() == 0) {

            JOptionPane.showConfirmDialog(null, "debes ingresar la categoría de las camas");
            jtfCategoriaC.requestFocus();
            return;
        }
        System.out.println("++++");

        if (jtfTipoHabitacion.getText().length() == 0) {
            
            JOptionPane.showConfirmDialog(null, "debes ingresar la categoría de la habitacion");
            jtfTipoHabitacion.requestFocus();
            return;
        }
        System.out.println("+++++");
        
        //si el texto del boton = Modificar , modifica el tipoHab
        if(jbModificar.getText()==m){
        
        TipoHabitacion thactual = new TipoHabitacion();     
        thactual.setCodigo(jtfCodigo.getText());
        thactual.setCantPersonas(jcCantP.getSelectedItem().toString());
        thactual.setCantCamas(jtfCantC.getText());
        thactual.setCategoriaCama(jtfCategoriaC.getText());
        thactual.setTipoHabitacion(jtfTipoHabitacion.getText());
        try {
////           thactual.setPrecioNoche(Integer.parseInt(jtfPrecio.getText()));
           thactual.setPrecioNoche(Double.parseDouble(jtfPrecio.getText()));
        } catch (NumberFormatException e) {
            mensaje("Debe ingresar un número decimal" + e);
        }        //
        
         TipoHabitacionData thd = new TipoHabitacionData();

        System.out.println("3");

        if (thd.modificar(thactual)) {
            JOptionPane.showMessageDialog(null, "Habitación modificada exitosamente");
            mostrar("");
            LimpiarCampos();
        }
                    mostrar("");

        }else if ( jbModificar.getText()== n){
        //jbNuevo.setEnabled(true);
        //jbModificar.setEnabled(true);
        TipoHabitacion thactual = new TipoHabitacion();
        TipoHabitacionData thd = new TipoHabitacionData();

        thactual.setCodigo(jtfCodigo.getText());
        thactual.setCantPersonas(jcCantP.getSelectedItem().toString());
        thactual.setCantCamas(jtfCantC.getText());
        thactual.setCategoriaCama(jtfCategoriaC.getText());
        thactual.setTipoHabitacion(jtfTipoHabitacion.getText());

        try {
          // thactual.setPrecioNoche(Integer.parseInt(jtfPrecio.getText()));
           thactual.setPrecioNoche(Double.parseDouble(jtfPrecio.getText()));
        } catch (NumberFormatException e) {
            mensaje("Debe ingresar un número decimal" + e);
        }

        if (thd.guardar(thactual)) {
            JOptionPane.showMessageDialog(null, "Habitación guardada exitosamente");
            mostrar("");
            LimpiarCampos();
        }    
        
        }
        
        
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
//funciona
        if (!jtfCodigo.getText().equals("")) {
            int confirmar = JOptionPane.showConfirmDialog(this, "Confirme si quiere eliminar", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmar == 0) {
                thactual = new TipoHabitacion();
                thd = new TipoHabitacionData();

                thactual.setCodigo(jtfCodigo.getText());
                thd.eliminar(thactual);
                mostrar("");
            }
        }


    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtListaTipoHabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaTipoHabMouseClicked

     ///   jbNuevo.setEnabled(false);
        jbModificar.setEnabled(true);
        jbModificar.setText(m);
        
        jbEliminar.setEnabled(true);
        jtfCodigo.setVisible(true);
        jtfPrecio.setVisible(true);
        jtfCantC.setVisible(true);
        jtfCategoriaC.setVisible(true);
        jtfTipoHabitacion.setVisible(true);
        jbEliminar.setEnabled(true);

        int fila = jtListaTipoHab.rowAtPoint(evt.getPoint());

        //jt   .setText(jtListaTipoHab.getValueAt(fila, 0));
        jtfCodigo.setText(jtListaTipoHab.getValueAt(fila, 1).toString());
        jcCantP.setSelectedItem(jtListaTipoHab.getValueAt(fila, 2).toString());
        jtfCantC.setText(jtListaTipoHab.getValueAt(fila, 3).toString());
        jtfCategoriaC.setText(jtListaTipoHab.getValueAt(fila, 4).toString());
        jtfTipoHabitacion.setText(jtListaTipoHab.getValueAt(fila, 5).toString());
        jtfPrecio.setText(jtListaTipoHab.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_jtListaTipoHabMouseClicked

    private void jbLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTablaActionPerformed
        borrarFilaTabla();
        jtfBuscar.setText("");
        mostrar("");
    }//GEN-LAST:event_jbLimpiarTablaActionPerformed

    private void jbCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarActionPerformed

        if (jtfBuscar.getText().length() == 0) {
            mensaje("Debe ingresar un tipo de habitación");
            jtfCodigo.requestFocus();
        }
        mostrar(jtfBuscar.getText());
//         mostrar("");
    }//GEN-LAST:event_jbCargarActionPerformed

    private void jtfCantCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCantCKeyTyped

    private void jtfPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfPrecioKeyTyped

    private void jtfCategoriaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCategoriaCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCategoriaCKeyTyped

    private void jtfTipoHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTipoHabitacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfTipoHabitacionKeyTyped

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || (c == '.' && jtfCodigo.getText().indexOf('.') == -1)) {
            evt.consume();
        }
        jtfCodigo.transferFocus();
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void jtfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioActionPerformed

    private void jtfBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != ' ') { // Permite escribir SOLo caracteres y espacios
            evt.consume();
        }
    }//GEN-LAST:event_jtfBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFID;
    private javax.swing.JButton jbCargar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbLimpiarTabla;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jblimpiar;
    private javax.swing.JComboBox<String> jcCantP;
    private javax.swing.JTable jtListaTipoHab;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfCantC;
    private javax.swing.JTextField jtfCategoriaC;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfTipoHabitacion;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
